version: "3"

services:
  app: # 컨테이너1 : app
    build:
      context: .
      dockerfile: ./src/Dockerfile
    links:
      - "db:mysqldb"
    ports:
      - "80:8080"
    container_name: app
    depends_on:
      - db

  db: # 컨테이너2 : db
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
    ports:
      - "33006:3306"
    container_name: db